[phases.setup]
nixPkgs = ["python310", "pip"]

[phases.install]
cmds = ["pip install -r backend/faster-whisper/requirements.txt"]

[start]
cmd = "uvicorn backend.faster-whisper.main:app --host 0.0.0.0 --port $PORT"